apps/curso/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
from .transaccional.views import *
urlpatterns = [
    url(r'^salon/registrar/$', login_required(Salon_Registro.as_view()), name='salon_crear'),
    url(r'^salon/editar/(?P<pk>\d+)/$', login_required(Salon_Actualizar.as_view()), name='salon_editar'),
    url(r'^salon/listado', login_required(Salon_Listado.as_view()), name='salon_listado'),
    url(r'^salon/eliminar/(?P<pk>\d+)/$', login_required(Salon_Eliminar.as_view()), name='salon_eliminar'),

    url(r'^registrar/$', login_required(Curso_Crear.as_view()), name='curso_crear'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(Curso_Actualizar.as_view()), name='curso_crear'),
    url(r'^listado', login_required(Curso_Listado.as_view()), name='curso_listado'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(Curso_Eliminar.as_view()), name='curso_eliminar'),
    url(r'^catalogo-cursos/$', login_required(Catalogo_curso), name='curso_catalogo'),
    url(r'^datos-curso/$', login_required(DatosCurso), name='curso_datos'),

    url(r'^niveles/([0-9]+)/$', login_required(Curso_Crear_Niveles), name='niveles_crear'),
    url(r'^niveles/([0-9]+)/editar/([0-9]+)/$', login_required(Curso_Actualizar_Niveles), name='niveles_editar'),
    url(r'^niveles/(?P<r_pk>\d+)/eliminar/(?P<pk>\d+)/$', login_required(Curso_Eliminar_Niveles.as_view()), name='niveles_eliminar'),

    url(r'^profesor/listado', login_required(Profesor_Listado.as_view()), name='profesor_listado'),
    url(r'^profesor/registrar/$', login_required(Profesor_Crear.as_view()), name='profesor_crear'),
    url(r'^profesor/editar/(?P<pk>\d+)/$', login_required(Profesor_Actualizar.as_view()), name='profesor_editar'),
    url(r'^profesor/eliminar/(?P<pk>\d+)/$', login_required(Profesor_Eliminar.as_view()), name='profesor_eliminar'),

    url(r'^horario/listado', login_required(Horario_Listado.as_view()), name='horario_listado'),
    url(r'^horario/registrar/$', login_required(Horario_Crear), name='horario_crear'),
    url(r'^horario/editar/(?P<pk>\d+)/$', login_required(Horario_Actualizar.as_view()), name='horario_editar'),
    url(r'^horario/eliminar/(?P<pk>\d+)/$', login_required(Horario_Eliminar.as_view()), name='horario_eliminar'),
    url(r'^horario/(?P<r_pk>\d+)/eliminar/detalle/(?P<pk>\d+)/$', login_required(Horario_Eliminar_Detalle.as_view()), name='horario_detalle_eliminar'),

    url(r'^pensum/listado', login_required(Pensum_Listado.as_view()), name='pensum_listado'),
    url(r'^pensum/registrar/$', login_required(Pensum_Crear), name='pensum_crear'),
    url(r'^pensum/editar/(?P<pk>\d+)/$', login_required(Pensum_Actualizar.as_view()), name='pensum_editar'),
    url(r'^pensum/eliminar/(?P<pk>\d+)/$', login_required(Pensum_Eliminar.as_view()), name='pensum_eliminar'),
    url(r'^pensum/(?P<r_pk>\d+)/eliminar/detalle/(?P<pk>\d+)/$', login_required(Pensum_Eliminar_Detalle.as_view()), name='pensum_detalle_eliminar'),
    url(r'^pensum/eliminar/detalle/([0-9])/$', login_required(Pensum_Eliminar_Todo_Pensum), name='pensum_detalle_total_eliminar'),

    url(r'^oferta/registrar/$', login_required(OfertaCurso_Registrar), name='OfertaCurso_crear'),
    url(r'^oferta/editar/([0-9])/$', login_required(OfertaCurso_Actualizar), name='OfertaCurso_crear'),
    url(r'^oferta/listado', login_required(OfertaCursoListado.as_view()), name='OfertaCurso_listado'),

    url(r'^alumno/registrar/$', login_required(Alumno_Registrar.as_view()), name='alumno_crear'),

    url(r'^configuracion/$', login_required(Configuracion_Academico), name='academico_configuracion'),
]

shool_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^', include('apps.sistema.urls', namespace='sistemas')),
    url(r'^curso/', include('apps.curso.urls', namespace='curso')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^administrativo/', include('apps.administracion.urls', namespace='administracion')),
]

apps/curso/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from apps.administracion.models import ConceptoFactura
# Create your models here.

class Configuracion(models.Model):
    oferta_salon_culminar_clases = models.IntegerField(default=0,null=False, blank=False,
                                                       verbose_name=_('Permitir oferta salon antes de culminar clases'))
    extiende_inscripcion = models.IntegerField(default=0, null=False, blank=False,
                                               verbose_name=_('Días que se extenderá las inscripciones para completar '
                                                              'capacidad máxima del salon'))
    configuracio_aplicada = models.BooleanField(default=False)

    class Meta:
        db_table = 'tb_cde_configuracion'
        verbose_name = 'Configuracion'
        verbose_name_plural = 'Configuraciones'

class Pensum(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    codigo_pensum = models.CharField(max_length=4, null=False, blank=False, unique=True, db_index=True,
                                     verbose_name='Código de pensum')
    descripcion = models.CharField(max_length=40, null=False, blank=False, verbose_name='Descripción del pensum')
    hora_semanal = models.IntegerField(null=False, blank=False, verbose_name='Horas semanal')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo_pensum+' / '+self.descripcion+', '+str(self.hora_semanal)+' Horas semanales'

    class Meta:
        db_table = 'tb_cde_pensum'
        verbose_name = 'Pensum'
        verbose_name_plural = 'Pensums'


class Pensum_detalle(models.Model):
    numero_unidad = models.IntegerField(null=False, blank=False, verbose_name='Unidad')
    actividad = models.CharField(max_length=40, null=False, blank=False, verbose_name='Actividad')
    numero_clase = models.IntegerField(null=False, blank=False, verbose_name='Número de clase')
    codigo_pensum = models.ForeignKey('Pensum', to_field='codigo_pensum', db_index=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'tb_cde_pensum_detalle'
        verbose_name = 'Pensum detalle'
        verbose_name_plural = 'Pensums detalle'

class Curso(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    codigo_curso = models.CharField(max_length=4, null=False, blank=False, unique=True, db_index=True,
                                    verbose_name='Código del curso')
    descripcion = models.CharField(max_length=40, null=False, blank=False, verbose_name='Nombre del curso')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')
    id = models.AutoField(primary_key=True)
    concepto_inscripcion = models.ForeignKey(ConceptoFactura, to_field='codigo_concepto', on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.codigo_curso+' / '+self.descripcion

    class Meta:
        db_table = 'tb_cde_curso'
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

class Nivel(models.Model):
    codigo_nivel = models.CharField(max_length=7, null=False, blank=False, unique=True, db_index=True,
                                    verbose_name='Código de nivel')
    descripcion = models.CharField(max_length=40, null=False, blank=False, verbose_name='Descripción del nivel')
    min_persona = models.IntegerField(null=False, blank=False, verbose_name='Mínimo para aperturar')
    meses_duracion = models.IntegerField(null=False, blank=False, verbose_name='Duración en meses')
    pensum = models.ManyToManyField(Pensum, verbose_name='Pensum aplicables para el nivel')
    monto_credito = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True,)
    monto_contado = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True,)
    excento_iva = models.BooleanField(default=False, verbose_name=_('Excento de I.V.A'))
    codigo_curso = models.ForeignKey(Curso,to_field='codigo_curso',  on_delete=models.CASCADE)

    def __str__(self):  # __unicode__ on Python 2
        return self.codigo_nivel

    class Meta:
        db_table = 'tb_cde_nivel'
        verbose_name = 'Nivel'
        verbose_name_plural = 'Niveles'

class Salon(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    codigo_salon = models.CharField(max_length=4, unique=True, verbose_name='Código del salon', db_index=True)
    nombre_salon = models.CharField(max_length=40, null=False, blank=False)
    capacidad = models.IntegerField(null=False, blank=False, verbose_name='Capacidad de alumnos', help_text='Es campo requerido')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo_salon+' / '+self.nombre_salon

    class Meta:
        db_table = 'tb_cde_salon'
        verbose_name = 'Salon'
        verbose_name_plural = 'Salones'


class Horario(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )

    codigo_horario = models.CharField(max_length=4, unique=True, db_index=True, verbose_name=_('Código horario'))
    descripcion = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Descripción'))
    salon = models.ManyToManyField(Salon)
    nivel = models.ManyToManyField(Nivel)
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo_horario+' / '+self.descripcion

    class Meta:
        db_table = 'tb_cde_horario'
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'


class Horario_detalle(models.Model):
    dia_semana = models.CharField(max_length=10, null=False, blank=False, verbose_name='Día de la semana')
    hora_inicio = models.CharField(max_length=10, null=False, blank=False, verbose_name='Hora de inicio')
    hora_culminacion = models.CharField(max_length=10, null=False, blank=False, verbose_name='Hora de culminación')
    codigo_horario = models.ForeignKey('Horario',to_field='codigo_horario', on_delete=models.CASCADE)

    class Meta:
        db_table = 'tb_cde_horario_detalle'
        verbose_name = 'Detalle horario'


class Profesor(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    cedula_profesor = models.CharField(max_length=10, null=False, blank=False, db_index=True,
                                       verbose_name='ID')
    nombre_profesor = models.CharField(max_length=60, null=False, blank=False, verbose_name='Nombre del Profesor')
    apellido_profesor = models.CharField(max_length=60, null=False, blank=False, verbose_name='Apellido del Profesor')
    direccion_habitacion = models.CharField(max_length=200, null=False, blank=False, verbose_name='Dirección')
    telefono = models.CharField(max_length=16, null=False, blank=False, verbose_name='Número de teléfono fijo')
    movil = models.CharField(max_length=16, null=False, blank=False, verbose_name='Número de teléfono movil')
    correo = models.CharField(max_length=60, null=False, blank=False, verbose_name='Correo electrónico')
    fecha_nacimiento = models.DateField(null=False, blank=False, verbose_name='Fecha de nacimiento')
    estado = models.CharField(max_length=1, choices=STATUS, default='A', verbose_name='Estado')
    id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'tb_cde_profesor'
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'


class Alumno(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )

    cedula_alumno = models.CharField(max_length=14, unique=True, null=False, blank=False, db_index=True, verbose_name='ID')
    nombre_alumno = models.CharField(max_length=60, null=False, blank=False, verbose_name='Nombre del Alumno')
    apellido_alumno = models.CharField(max_length=60, null=False, blank=False, verbose_name='Apellido del Alumno')
    direccion_habitacion = models.CharField(max_length=200, null=False, blank=False, verbose_name='Dirección')
    telefono = models.CharField(max_length=14, verbose_name='Número de teléfono fijo')
    telefono_opcional = models.CharField(max_length=14, null=True, blank=True,verbose_name='Número de teléfono opcional')
    movil = models.CharField(max_length=14, verbose_name='Número de teléfono movil')
    correo = models.CharField(max_length=60, null=False, blank=False, verbose_name='Correo electrónico')
    fecha_nacimiento = models.DateField(null=False, blank=False, verbose_name='Fecha de nacimiento')
    trabaja_guardia = models.BooleanField(default=False, verbose_name= 'Trabaja por guardia')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')
    id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'tb_cde_alumno'
        verbose_name = 'Alumno'
        verbose_name_plural = 'Alumnos'

apps/curso/transaccional/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from apps.curso.models import Salon, Nivel, Horario, Pensum, Alumno, Profesor, Pensum_detalle

class OfertaCurso(models.Model):
    INSCRIPCION = 'I'
    SUSPENDIDO = 'S'
    FINALIZADO = 'F'
    PROCESO_CLASE = 'P'
    CUPOS_COMPLETADOS = 'C'
    STATUS = (
        (INSCRIPCION, 'Inscripcion'),
        (SUSPENDIDO, 'Suspendido'),
        (FINALIZADO, 'Finalizado'),
        (PROCESO_CLASE, 'Proceso de clases'),
        (CUPOS_COMPLETADOS, 'Cupos completados'),
    )
    cupos = models.IntegerField(verbose_name= _('Cantidad de cupos'), blank=True, null=True)
    edad_minima = models.IntegerField(verbose_name= _('Edad mínima permitida'), blank=True, null=True)
    edad_max = models.IntegerField(verbose_name= _('Edad máxima permitida'), blank=True, null=True)
    estado = models.CharField(max_length=1, db_index= True, choices=STATUS, default='I')
    cierre_inscripcion = models.DateField(null=True, blank=True)
    salon = models.ForeignKey(Salon, to_field= 'codigo_salon',null=True, blank=True, on_delete=models.PROTECT)
    profesor = models.ForeignKey(Profesor, on_delete=models.PROTECT, blank=True, null=True)
    nivel = models.ForeignKey(Nivel, to_field='codigo_nivel', db_index=True, on_delete=models.PROTECT)
    horario = models.ForeignKey(Horario, to_field='codigo_horario', db_index= True, null=True, blank=True, on_delete=models.PROTECT)
    pensum = models.ForeignKey(Pensum, to_field ='codigo_pensum', on_delete=models.PROTECT)

    class Meta:
        db_table = 'tb_cde_oferta_curso'
        verbose_name = 'Oferta de curso'
        verbose_name_plural = 'Cursos ofertados'


class Inscripcion(models.Model):
    Aprovado = 'A'
    Repobado = 'R'
    Desertor = 'D'
    En_Curso = 'C'
    solo_contrato = 'T'
    Congelado = 'G'
    Anulado = 'X' #si el contrato va por su segundo nivel no se puede anular 'ojo'

    STATUS = (
        (Aprovado, 'Aprovado'),
        (Repobado, 'Suspendido'),
        (Desertor, 'Finalizado'),
        (En_Curso, 'En curso'),
        (solo_contrato, 'Temporal solo hizo contrato'),
        (Congelado,'Congelado'),
        (Anulado, 'Anulado'),
    )
    alumno = models.ForeignKey(Alumno, db_index= True)
    nivel_siguiente = models.ForeignKey(Nivel, on_delete=models.PROTECT)
    oferta = models.ForeignKey(OfertaCurso, db_index=True)
    fecha_inicio = models.DateField(verbose_name= _('Fecha de inicio de clases'))
    fecha_culminacion = models.DateField(verbose_name= _('Fecha de culminación de clases'))
    estado = models.CharField(max_length=1, db_index=True, choices=STATUS, default='T')
    genera_financiamiento = models.CharField

    class Meta:
        db_table = 'tb_cde_inscripcion'
        verbose_name = 'Inscripcion'
        verbose_name_plural = 'Inscripciones'


class Cronograma(models.Model):
    fecha_clase = models.DateField(null=False, blank=False)
    pensum_detalle = models.ForeignKey(Pensum_detalle, on_delete=models.PROTECT)
    oferta = models.ForeignKey(OfertaCurso, on_delete=models.CASCADE)

    class Meta:
        db_table = 'tb_cde_cronograma'
        verbose_name = 'Cronograma actividad'
        verbose_name_plural = 'Cronogramas de Actividades'

apps/curso/transaccional/forms.py
from django import forms
from django.utils.translation import ugettext_lazy as _
from django.contrib import messages
from .models import OfertaCurso
from ..models import Salon, Horario, Curso

class OfertarCursoForm(forms.ModelForm):
    class Meta:
        model = OfertaCurso
        fields = ['estado','cupos', 'nivel','pensum']

        widgets = {
            'cupos': forms.TextInput(attrs={'class': 'form-control', 'readonly':'readonly', 'value' : 0}),
        }

    def __init__(self, *args, **kwargs):
        super(OfertarCursoForm, self).__init__(*args, **kwargs)

        for campo in self.fields:
            self.fields[campo].widget.attrs.update({'class' : 'form-control','required' : 'required'})

apps/curso/templates/curso/transaccion/ofertar_curso.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "Ofertar Cursos" %}<small></small></h2>

</div>
<form method="post" id="form_ofertas" action="" class="form-horizontal form-label-left input_mask" autocomplete="off">
    {% csrf_token %}
    <p class="col-md-3 col-sm-6 col-sx-12">
        <label>{% trans 'Curso' %}</label>
        <input type="text" autofocus = "on" name="curso"  id="id_curso" placeholder="{% trans 'Código de curso' %}" class = "form-control"
        required = "required" value="{{datos.codigo_curso}}">

    </p>
    <p class="col-md-9 col-sm-6 col-sx-12">
        <label>{% trans 'Descripción' %}</label>
        <input type="text" readonly = "readonly" class = "form-control" id="descripcion" value="{{datos.descripcion}}">
    </p>

    <p class="col-md-3 col-sm-6 col-sx-12">
        <label>{{ form.nivel.label }}</label>

        <select id="id_nivel" name="nivel" required = "required" class="form-control">
            <option>---------</option>
            {% if accion != '' %}
               {% for nivel in niveles %}
                    {% if datos.nivel_id == nivel.codigo_nivel %}
                        <option selected = "selected" value = "{{nivel.codigo_nivel}}">{{nivel.codigo_nivel}}  / {{nivel.descripcion}}</option>
                    {% else %}
                        <option value = "{{nivel.codigo_nivel}}">{{nivel.codigo_nivel}}  / {{nivel.descripcion}}</option>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </select>
    </p>
    <p class="col-md-3 col-sm-4 col-sx-12">
        <label>{{ form.pensum.label }}</label>
        <select id="id_pensum" name="pensum" required = "required" class="form-control">
            <option>---------</option>
            {% if accion != '' %}
               {% for pensum in pensum %}
                    {% if datos.pensum_id == pensum.codigo_pensum %}
                        <option selected = "selected" value = "{{pensum.codigo_pensum}}">{{pensum.codigo_pensum}}  / {{pensum.descripcion}}</option>
                    {% else %}
                        <option value = "{{pensum.codigo_nivel}}">{{pensum.codigo_pensum}}  / {{pensum.descripcion}}</option>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </select>
    </p>
    <div class="clear"></div>
    <p class="col-md-3 col-sm-4 col-sx-6">
        <label>{{ form.cupos.label }}</label>

        <input class="form-control" id="id_cupos" name="cupos" readonly="readonly" required="required" type="text" value="{{datos.cupos}}">
    </p>
    <p class="col-md-3 col-sm-4 col-sx-6">
        <label>{{ form.estado.label }}</label>
        {{form.estado}}

    </p>

    <div class="clear"></div>
    <fieldset id="detalle_horario" style="display: none">
        <legend>Detalle del horario</legend>
        <div  class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Día de la semana</th>
                        <th>Hora de inicio</th>
                        <th>Hora de culminación</th>
                    </tr>
                </thead>
                <tbody></tbody>
            </table>
        </div>
    </fieldset>
    <div class="clear"></div>

    <div class="ln_solid"></div>
    <div style="text-align:center">
        {% if accion == 'actualizar' %}
        <button type="submit" class="btn btn-success">{% trans "Actualizar"%}</button>
        {% else %}
        <button type="submit" class="btn btn-success">{% trans "Crear Ofertar de Curso"%}</button>
        {% endif %}
        <a href="/curso/oferta/listado/" class="btn btn-primary">{% trans "Listado de ofertas creadas"%}</a>
        <a href="/curso/oferta/registrar/" class="btn btn-default">{% trans "Limpiar"%}</a>
    <div>
</form>
{% endblock contenido %}
{% block js %}
<script>
    $(function(){
        {% if accion != '' %}
            $("#id_estado option[value='{{datos.estado}}']").prop('selected', true);
        {% endif %}
        setTransferFocus($('#form_ofertas'));
        $("#id_curso").mask("C999");
        $('#id_curso').keydown(function(e){
            if(e.keyCode == 13 && $(this).val().trim() != '')
                buscarDatoCurso($(this).val());
            if (e.keyCode == teclaCtrl)
            ctrlPressed = true;
            if (ctrlPressed && (e.keyCode == teclaF1)){
                $('#busqueda_sensitiva').val('');
                catalogoCurso(1, '');
            }
        });

        $('#id_nivel').change(function(){
            if ($(this).val() == ''){
                $('#id_pensum').html('')
                return;
            }
            NProgress.start();
            $.ajax({
                url: '/curso/oferta/registrar/',
                type: 'post',
                dataType: 'json',
                data: {nivel:$(this).val(),accion:'getPensums', csrfmiddlewaretoken:'{{csrf_token}}'},
                success: function (response) {
                    NProgress.done();
                    $('#id_pensum').html(response.datos)
                    $('#id_cupos').val(response.cupos);
                    NProgress.done();


                }
            });
        });

        $('#id_horario').change(function(){
            if ($(this).val() == ''){
                $('#id_horario').html('')
                return;
            }
            NProgress.start();
            $.ajax({
                url: '/curso/oferta/registrar/',
                type: 'post',
                dataType: 'json',
                data: {horario:$(this).val(),accion:'getDetalleHorario', csrfmiddlewaretoken:'{{csrf_token}}'},
                success: function (response) {
                    NProgress.done();
                    $('.table tbody').html(response.datos);
                    $('#detalle_horario').fadeIn();
                    NProgress.done();
                }
            });
        });
            

    });
    function buscarDatoCurso (){
        NProgress.start();
        $.ajax({
            url: '/curso/datos-curso/',
            type: 'post',
            dataType: 'json',
            data:  {csrfmiddlewaretoken:'{{csrf_token}}', codigo_curso:$('#id_curso').val()},
            success: function (data) {
                NProgress.done();
                if(data.mensaje == ''){
                    $('#descripcion').val(data.nombre_curso);
                    getListadoNiveles();
                }else{
                    mostrarMensaje(data.mensaje);
                }
            }
        });
    }
    function catalogoCurso(pagina, frase){
        NProgress.start();
        $.ajax({
            url: '/curso/catalogo-cursos/',
            type: 'post',
            dataType: 'json',
            data:  {pagina: pagina, frase:frase, csrfmiddlewaretoken:'{{csrf_token}}'},
            success: function (data) {
                NProgress.done();
                if(data.mensaje == ''){
                    footerPaginacionAjax( data.pagina, 'catalogoCurso');
                    $('#from_catalogo table > thead').html('<tr><th>{% trans "Código curso"%}</th><th>{% trans "Descripción del curso"%}</th></tr>');
                    $('#listado tbody').html(data.datos);
                    $('#from_catalogo').modal('show');
                    $('#busqueda_sensitiva').focus()
                }else{
                    mostrarMensaje(data.mensaje);
                }
            }
        });
    }
    function seleccion_curso(codigo, descripcion){
        $('#id_curso').val(codigo);
        $('#descripcion').val(descripcion);
        $('#from_catalogo').modal('hide');
        getListadoNiveles();
    }
    function getListadoNiveles(){
         NProgress.start();
        $.ajax({
            url: '/curso/oferta/registrar/',
            type: 'post',
            dataType: 'json',
            data: {curso: $('#id_curso').val(),accion:'getNiveles', csrfmiddlewaretoken:'{{csrf_token}}'},
            success: function (response) {
                NProgress.done();
                $('#id_nivel').html(response.datos)
                NProgress.done();


            }
        });
    }

</script>
{% endblock js %}