apps/curso/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *
from .transaccional.views import *
urlpatterns = [
    url(r'^salon/registrar/$', login_required(Salon_Registro.as_view()), name='salon_crear'),
    url(r'^salon/editar/(?P<pk>\d+)/$', login_required(Salon_Actualizar.as_view()), name='salon_editar'),
    url(r'^salon/listado', login_required(Salon_Listado.as_view()), name='salon_listado'),
    url(r'^salon/eliminar/(?P<pk>\d+)/$', login_required(Salon_Eliminar.as_view()), name='salon_eliminar'),

    url(r'^registrar/$', login_required(Curso_Crear.as_view()), name='curso_crear'),
    url(r'^editar/(?P<pk>\d+)/$', login_required(Curso_Actualizar.as_view()), name='curso_crear'),
    url(r'^listado', login_required(Curso_Listado.as_view()), name='curso_listado'),
    url(r'^eliminar/(?P<pk>\d+)/$', login_required(Curso_Eliminar.as_view()), name='curso_eliminar'),
    url(r'^catalogo-cursos/$', login_required(Catalogo_curso), name='curso_catalogo'),
    url(r'^datos-curso/$', login_required(DatosCurso), name='curso_datos'),

    url(r'^niveles/([0-9]+)/$', login_required(Curso_Crear_Niveles), name='niveles_crear'),
    url(r'^niveles/([0-9]+)/editar/([0-9]+)/$', login_required(Curso_Actualizar_Niveles), name='niveles_editar'),
    url(r'^niveles/(?P<r_pk>\d+)/eliminar/(?P<pk>\d+)/$', login_required(Curso_Eliminar_Niveles.as_view()), name='niveles_eliminar'),

    url(r'^profesor/listado', login_required(Profesor_Listado.as_view()), name='profesor_listado'),
    url(r'^profesor/registrar/$', login_required(Profesor_Crear.as_view()), name='profesor_crear'),
    url(r'^profesor/editar/(?P<pk>\d+)/$', login_required(Profesor_Actualizar.as_view()), name='profesor_editar'),
    url(r'^profesor/eliminar/(?P<pk>\d+)/$', login_required(Profesor_Eliminar.as_view()), name='profesor_eliminar'),

    url(r'^horario/listado', login_required(Horario_Listado.as_view()), name='horario_listado'),
    url(r'^horario/registrar/$', login_required(Horario_Crear), name='horario_crear'),
    url(r'^horario/editar/(?P<pk>\d+)/$', login_required(Horario_Actualizar.as_view()), name='horario_editar'),
    url(r'^horario/eliminar/(?P<pk>\d+)/$', login_required(Horario_Eliminar.as_view()), name='horario_eliminar'),
    url(r'^horario/(?P<r_pk>\d+)/eliminar/detalle/(?P<pk>\d+)/$', login_required(Horario_Eliminar_Detalle.as_view()), name='horario_detalle_eliminar'),

    url(r'^pensum/listado', login_required(Pensum_Listado.as_view()), name='pensum_listado'),
    url(r'^pensum/registrar/$', login_required(Pensum_Crear), name='pensum_crear'),
    url(r'^pensum/editar/(?P<pk>\d+)/$', login_required(Pensum_Actualizar.as_view()), name='pensum_editar'),
    url(r'^pensum/eliminar/(?P<pk>\d+)/$', login_required(Pensum_Eliminar.as_view()), name='pensum_eliminar'),
    url(r'^pensum/(?P<r_pk>\d+)/eliminar/detalle/(?P<pk>\d+)/$', login_required(Pensum_Eliminar_Detalle.as_view()), name='pensum_detalle_eliminar'),
    url(r'^pensum/eliminar/detalle/([0-9])/$', login_required(Pensum_Eliminar_Todo_Pensum), name='pensum_detalle_total_eliminar'),

    url(r'^oferta/registrar/$', login_required(OfertaCurso_Registrar), name='OfertaCurso_crear'),
    url(r'^oferta/editar/([0-9])/$', login_required(OfertaCurso_Actualizar), name='OfertaCurso_crear'),
    url(r'^oferta/listado', login_required(OfertaCursoListado.as_view()), name='OfertaCurso_listado'),

    url(r'^alumno/registrar/$', login_required(Alumno_Registrar.as_view()), name='alumno_crear'),

    url(r'^configuracion/$', login_required(Configuracion_Academico), name='academico_configuracion'),
]

shool_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^', include('apps.sistema.urls', namespace='sistemas')),
    url(r'^curso/', include('apps.curso.urls', namespace='curso')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^administrativo/', include('apps.administracion.urls', namespace='administracion')),
]

apps/curso/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from apps.administracion.models import ConceptoFactura
# Create your models here.

class Configuracion(models.Model):
    oferta_salon_culminar_clases = models.IntegerField(default=0,null=False, blank=False,
                                                       verbose_name=_('Permitir oferta salon antes de culminar clases'))
    extiende_inscripcion = models.IntegerField(default=0, null=False, blank=False,
                                               verbose_name=_('Días que se extenderá las inscripciones para completar '
                                                              'capacidad máxima del salon'))
    configuracio_aplicada = models.BooleanField(default=False)

    class Meta:
        db_table = 'tb_cde_configuracion'
        verbose_name = 'Configuracion'
        verbose_name_plural = 'Configuraciones'

class Pensum(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    codigo_pensum = models.CharField(max_length=4, null=False, blank=False, unique=True, db_index=True,
                                     verbose_name='Código de pensum')
    descripcion = models.CharField(max_length=40, null=False, blank=False, verbose_name='Descripción del pensum')
    hora_semanal = models.IntegerField(null=False, blank=False, verbose_name='Horas semanal')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo_pensum+' / '+self.descripcion+', '+str(self.hora_semanal)+' Horas semanales'

    class Meta:
        db_table = 'tb_cde_pensum'
        verbose_name = 'Pensum'
        verbose_name_plural = 'Pensums'


class Pensum_detalle(models.Model):
    numero_unidad = models.IntegerField(null=False, blank=False, verbose_name='Unidad')
    actividad = models.CharField(max_length=40, null=False, blank=False, verbose_name='Actividad')
    numero_clase = models.IntegerField(null=False, blank=False, verbose_name='Número de clase')
    codigo_pensum = models.ForeignKey('Pensum', to_field='codigo_pensum', db_index=True, on_delete=models.CASCADE)

    class Meta:
        db_table = 'tb_cde_pensum_detalle'
        verbose_name = 'Pensum detalle'
        verbose_name_plural = 'Pensums detalle'

class Curso(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    codigo_curso = models.CharField(max_length=4, null=False, blank=False, unique=True, db_index=True,
                                    verbose_name='Código del curso')
    descripcion = models.CharField(max_length=40, null=False, blank=False, verbose_name='Nombre del curso')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')
    id = models.AutoField(primary_key=True)
    concepto_inscripcion = models.ForeignKey(ConceptoFactura, to_field='codigo_concepto', on_delete=models.PROTECT, blank=True, null=True)

    def __str__(self):
        return self.codigo_curso+' / '+self.descripcion

    class Meta:
        db_table = 'tb_cde_curso'
        verbose_name = 'Curso'
        verbose_name_plural = 'Cursos'

class Nivel(models.Model):
    codigo_nivel = models.CharField(max_length=7, null=False, blank=False, unique=True, db_index=True,
                                    verbose_name='Código de nivel')
    descripcion = models.CharField(max_length=40, null=False, blank=False, verbose_name='Descripción del nivel')
    min_persona = models.IntegerField(null=False, blank=False, verbose_name='Mínimo para aperturar')
    meses_duracion = models.IntegerField(null=False, blank=False, verbose_name='Duración en meses')
    pensum = models.ManyToManyField(Pensum, verbose_name='Pensum aplicables para el nivel')
    monto_credito = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True,)
    monto_contado = models.DecimalField(max_digits=10, decimal_places=3, null=True, blank=True,)
    excento_iva = models.BooleanField(default=False, verbose_name=_('Excento de I.V.A'))
    codigo_curso = models.ForeignKey(Curso,to_field='codigo_curso',  on_delete=models.CASCADE)

    def __str__(self):  # __unicode__ on Python 2
        return self.codigo_nivel

    class Meta:
        db_table = 'tb_cde_nivel'
        verbose_name = 'Nivel'
        verbose_name_plural = 'Niveles'

class Salon(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    codigo_salon = models.CharField(max_length=4, unique=True, verbose_name='Código del salon', db_index=True)
    nombre_salon = models.CharField(max_length=40, null=False, blank=False)
    capacidad = models.IntegerField(null=False, blank=False, verbose_name='Capacidad de alumnos', help_text='Es campo requerido')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo_salon+' / '+self.nombre_salon

    class Meta:
        db_table = 'tb_cde_salon'
        verbose_name = 'Salon'
        verbose_name_plural = 'Salones'


class Horario(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )

    codigo_horario = models.CharField(max_length=4, unique=True, db_index=True, verbose_name=_('Código horario'))
    descripcion = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Descripción'))
    salon = models.ManyToManyField(Salon)
    nivel = models.ManyToManyField(Nivel)
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    def __str__(self):
        return self.codigo_horario+' / '+self.descripcion

    class Meta:
        db_table = 'tb_cde_horario'
        verbose_name = 'Horario'
        verbose_name_plural = 'Horarios'


class Horario_detalle(models.Model):
    dia_semana = models.CharField(max_length=10, null=False, blank=False, verbose_name='Día de la semana')
    hora_inicio = models.CharField(max_length=10, null=False, blank=False, verbose_name='Hora de inicio')
    hora_culminacion = models.CharField(max_length=10, null=False, blank=False, verbose_name='Hora de culminación')
    codigo_horario = models.ForeignKey('Horario',to_field='codigo_horario', on_delete=models.CASCADE)

    class Meta:
        db_table = 'tb_cde_horario_detalle'
        verbose_name = 'Detalle horario'


class Profesor(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    cedula_profesor = models.CharField(max_length=10, null=False, blank=False, db_index=True,
                                       verbose_name='ID')
    nombre_profesor = models.CharField(max_length=60, null=False, blank=False, verbose_name='Nombre del Profesor')
    apellido_profesor = models.CharField(max_length=60, null=False, blank=False, verbose_name='Apellido del Profesor')
    direccion_habitacion = models.CharField(max_length=200, null=False, blank=False, verbose_name='Dirección')
    telefono = models.CharField(max_length=16, null=False, blank=False, verbose_name='Número de teléfono fijo')
    movil = models.CharField(max_length=16, null=False, blank=False, verbose_name='Número de teléfono movil')
    correo = models.CharField(max_length=60, null=False, blank=False, verbose_name='Correo electrónico')
    fecha_nacimiento = models.DateField(null=False, blank=False, verbose_name='Fecha de nacimiento')
    estado = models.CharField(max_length=1, choices=STATUS, default='A', verbose_name='Estado')
    id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'tb_cde_profesor'
        verbose_name = 'Profesor'
        verbose_name_plural = 'Profesores'


class Alumno(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )

    cedula_alumno = models.CharField(max_length=14, unique=True, null=False, blank=False, db_index=True, verbose_name='ID')
    nombre_alumno = models.CharField(max_length=60, null=False, blank=False, verbose_name='Nombre del Alumno')
    apellido_alumno = models.CharField(max_length=60, null=False, blank=False, verbose_name='Apellido del Alumno')
    direccion_habitacion = models.CharField(max_length=200, null=False, blank=False, verbose_name='Dirección')
    telefono = models.CharField(max_length=14, verbose_name='Número de teléfono fijo')
    telefono_opcional = models.CharField(max_length=14, null=True, blank=True,verbose_name='Número de teléfono opcional')
    movil = models.CharField(max_length=14, verbose_name='Número de teléfono movil')
    correo = models.CharField(max_length=60, null=False, blank=False, verbose_name='Correo electrónico')
    fecha_nacimiento = models.DateField(null=False, blank=False, verbose_name='Fecha de nacimiento')
    trabaja_guardia = models.BooleanField(default=False, verbose_name= 'Trabaja por guardia')
    estado = models.CharField(max_length=1, choices=STATUS, default='A')
    id = models.AutoField(primary_key=True)

    class Meta:
        db_table = 'tb_cde_alumno'
        verbose_name = 'Alumno'
        verbose_name_plural = 'Alumnos'

apps/curso/transaccional/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from django.utils.translation import ugettext_lazy as _
from django.shortcuts import render
from django.contrib import messages
from django.db import connection, IntegrityError
from apps.sistema.util.Funciones import cursorDictFetchall
from .models import OfertaCurso
from ..models import Nivel, Pensum, Horario, Horario_detalle, Salon
from .forms import OfertarCursoForm
import json


def ajaxOfertaCurso(request):
    xHTML = '<option selected="selected" value="">---------</option>'
    if request.POST['accion'] == 'getNiveles':
        datos = Nivel.objects.filter(codigo_curso=request.POST['curso'])
        for nivel in datos:
            xHTML += '<option value = "' + str(
                nivel.codigo_nivel) + '">' + nivel.codigo_nivel + ' / ' + nivel.descripcion + '</option>'

    if request.POST['accion'] == 'getPensums':
        nivel = Nivel.objects.get(codigo_nivel=request.POST['nivel'])
        datos = Pensum.objects.filter(nivel__id = nivel.id, estado='A')
        for pensum in datos:
            xHTML += '<option value = "' + str(
                pensum.codigo_pensum) + '">' + pensum.codigo_pensum + ' / ' + pensum.descripcion + '</option>'

        ''' se busca la capacidad del salon seleccionado, la cual sera la cantidad de cupos disponibles
            a la venta para ese curss.
        '''

        return HttpResponse(json.dumps({'datos': xHTML,'cupos':nivel.min_persona}), content_type="application/json")

    if request.POST['accion'] == 'getDetalleHorario':
        datos = Horario_detalle.objects.filter(codigo_horario=request.POST['horario'])
        xHTML = ''
        for horario in datos:
            xHTML += '<tr><td>' + horario.dia_semana + '</td><td> ' + horario.hora_inicio + '</td><td> ' + horario.hora_culminacion + '</option>'

    return HttpResponse(json.dumps({'datos': xHTML}), content_type="application/json")


def OfertaCurso_Registrar(request):
    if request.is_ajax():
        return ajaxOfertaCurso(request)
    if request.method == 'POST':
        form = OfertarCursoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/curso/oferta/listado')
        else:
            messages.add_message(request, messages.WARNING, form.errors)

    context = {
        'titulo': _('Ofertar cursos'),
        'form': OfertarCursoForm,
        'accion': ''
    }
    return render(request, 'curso/transaccion/ofertar_curso.html', context)

def OfertaCurso_Actualizar(request, pk_oferta):
    if request.method == 'POST':
        form = OfertarCursoForm(request.POST, instance=OfertaCurso.objects.get(pk=pk_oferta))
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/curso/oferta/listado')
        else:
            messages.add_message(request, messages.WARNING, form.errors)

    cursor = connection.cursor()
    cursor.execute("SELECT a.id, a.nivel_id, pensum_id, c.codigo_curso, c.descripcion, a.estado, cupos "
                   "FROM tb_cde_oferta_curso a, tb_cde_nivel b, tb_cde_curso c "
                   "WHERE a.nivel_id = b.codigo_nivel and b.codigo_curso_id = c.codigo_curso "
                   "       and a.id =  %s ",
                   [int(pk_oferta)]
                   )
    datos = cursorDictFetchall(cursor)


    data_niveles = Nivel.objects.filter(codigo_curso=datos[0]['codigo_curso'])
    data_pensum = Pensum.objects.filter(codigo_pensum=datos[0]['pensum_id'])
    context = {
        'datos' : datos[0],
        'form' : OfertarCursoForm,
        'niveles' : data_niveles,
        'pensum' : data_pensum,
        'accion': 'actualizar',
    }
    return render(request, 'curso/transaccion/ofertar_curso.html', context)


class OfertaCursoListado(ListView):
    model = OfertaCurso
    template_name = 'curso/transaccion/ofertar_curso_listado.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(OfertaCursoListado, self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = _('Listado de cursos ofertados')

        return context

    #def get_queryset(self):
    #    pass

apps/curso/templates/curso/niveles.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "Asignar niveles al curso" %}<small></small></h2>

</div>
    <p class="col-md-2 col-sm-4 col-sx-12">
        <label>Código de curso</label>
        <input type="text" readonly = "readonly" name="codigo_curso" class="form-control"
        value="{{ data_curso.codigo_curso }}">

    </p>
    <p class="col-md-10 col-sm-8 col-sx-12">
        <label>Nombre del curso</label>
        <input type="text" readonly = "readonly" name="descripcion" class="form-control" value="{{ data_curso.descripcion }}">
    </p>
    <div class="clear"></div>
    <fieldset>
        <legend>{% trans "Listado de nivel" %}</legend>
        <div  class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>{% trans "Código de nivel" %}</th>
                        <th>{% trans "Descripción" %}</th>
                        <th>{% trans "Duración" %}</th>
                        <th>{% trans "Mínimo para aperturar" %}</th>
                        <th style="width:200px"></th>
                    </tr>
                </thead>
                <tbody>
        		    {% for nivel in listado_nivel %}
                    <tr>
                        <td>{{nivel.codigo_nivel}}</td>
                        <td>{{nivel.descripcion}}</td>
                        <td>{{nivel.meses_duracion}}</td>
                        <td>{{nivel.min_persona}}</td>
                        <td>
                            <a class="btn btn-icon" href="/curso/niveles/{{ data_curso.id }}/editar/{{ nivel.id }}/" title='{% trans "Editar" %}'>
                                <i class="fa fa-pencil-square-o"></i>
                                Editar
                            </a>
                            <a class="btn delete btn-icon" parametro = '{{ obj_paginador.id }}' href="/curso/niveles/{{ data_curso.id }}/eliminar/{{ nivel.id }}/" title='{% trans "Eliminar Niveles" %}'>
                                <i class="fa fa-eraser"></i>
                                Eliminar
                            </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </fieldset>

    <div class="ln_solid"></div>
    <div style="text-align:center">
        <a class="btn btn-success" id="add-nivel">{% trans "Agregar Nivel"%}</a>
        <a href="/curso/listado/" class="btn btn-primary">{% trans "Listado de cursos"%}</a>
    </div>

<div id="from_niveles" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title">{% trans "Agregar Nivel"%}</h4>
            </div>
            <div class="modal-body" style="padding: 0;">
                <form method="post" id="frm">
                    {% csrf_token %}
                    <input type="hidden" name="codigo_curso" value="{{ data_curso.codigo_curso }}">
                    <p class="col-md-4 col-sm-12 col-sx-12" style="margin-top:10px;">
                        <label>{{form_nivel.codigo_nivel.label}}</label>
                        {% if accion == 'editar_nivel' %}
                        <input type="text" class="form-control" autofocus = "on" name="codigo_nivel" id="id_codigo_nivel"
                               required = "required" value="{{data_nivel.codigo_nivel}}" readonly = "readonly">
                        {% else %}
                        <input type="text" class="form-control" maxlength="7"  id="id_codigo_nivel"
                         autofocus = "on" name="codigo_nivel" id="id_codigo_nivel" required = "required">
                        {% endif %}


                    </p>
                    <p class="col-md-8 col-sm-12 col-sx-12" style="margin-top:10px;">
                        <label>{{form_nivel.descripcion.label}}</label>
                        <input type="text" class="form-control" autofocus = "on" name="descripcion" id="id_descripcion"
                               required = "required" value="{{data_nivel.descripcion}}">

                    </p>
                    <p class="col-md-4 col-sm-6 col-sx-6">
                        <label>{{form_nivel.meses_duracion.label}}</label>
                        <input type="number" class="form-control" autofocus = "on" name="meses_duracion" id="id_meses_duracion"
                               required = "required" value="{{data_nivel.meses_duracion}}">

                    </p>
                    <p class="col-md-4 col-sm-6 col-sx-6">
                        <label>{{form_nivel.min_persona.label}}</label>
                        <input type="number" class="form-control" autofocus = "on" name="min_persona" id="id_min_persona"
                               required = "required" value="{{data_nivel.min_persona}}">
                    </p>
                    <p class="col-md-12 col-sm-12 col-sx-12">
                        <label>{{form_nivel.pensum.label}}</label>
                        {{form_nivel.pensum}}

                    </p>
                    <div class="clear"></div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default pull-left" data-dismiss="modal">Cerrar</button>
                <button type="button" class="btn btn-primary" id="enviar_frm">Guardar</button>
            </div>
        </div>
    </div>
</div>
{% endblock contenido %}


{% block js %}
<script>
    $(function(){
        $("#id_codigo_nivel").mask("C999-99");
        {% if accion == 'editar_nivel' %}
        $('#from_niveles').modal('show');
        {% endif %}
        $('#enviar_frm').click(function(){
            $('#frm').submit();
        })
        $('#add-nivel').click(function(){
            $('#from_niveles').modal('show');
            NProgress.done();
        })
    })
</script>
{% endblock js %}

apps/curso/templates/curso/profesor.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "Registro de Profesor" %}<small></small></h2>

</div>
<form method="post" id="form" action="" class="form-horizontal form-label-left input_mask">    
    {% csrf_token %}
    <p class="col-md-2 col-sm-4 col-sx-6">
        <label>{{ form.cedula_profesor.label }}</label>
        {% if accion == 'actualizar' %}
        <input type="text" maxlength="10" name="cedula_profesor" value="{{ form.cedula_profesor.value }}"
               class="form-control" readonly = "readonly" id="id_cedula_profesor" >
        {% else %}
        <input type="text" maxlength="10" name="cedula_profesor" class="form-control" id="id_cedula_profesor"
               required = "required" autofocus = "on" onKeyPress="return validarNumero(event)">
        {% endif %}

    </p>
    <div class="clear"></div>
    <p class="col-md-6 col-sm-6 col-xs-12">
        <label>{{form.nombre_profesor.label}}</label>
        {{form.nombre_profesor}}
    </p>
    <p class="col-md-6 col-sm-6 col-xs-12">
        <label>{{form.apellido_profesor.label}}</label>
        {{form.apellido_profesor}}
    </p>
    <p class="col-md-4 col-sm-6 col-xs-6">
        <label>{{form.telefono.label}}</label>
        {{form.telefono}}
    </p>
    <p class="col-md-4 col-sm-6 col-xs-6">
        <label>{{form.movil.label}}</label>
        {{form.movil}}
    </p>
    <p class="col-md-4 col-sm-6 col-xs-12">
        <label>{{form.correo.label}}</label>
        {{form.correo}}
    </p>
    <div class="clear"></div>
    <p class="col-md-3 col-sm-4 col-xs-6">
        <label>{{form.fecha_nacimiento.label}}</label>
        {{form.fecha_nacimiento}}
    </p>
    <p class="col-md-4 col-sm-4 col-xs-6">
        <label>{{form.estado.label}}</label>
        {{form.estado}}
    </p>
    <div class="clear"></div>
    <p class="col-md-12 col-sm-12 col-sx-12">
        <label>{{form.direccion_habitacion.label}}</label>
        {{form.direccion_habitacion}}
    </p>
    <div class="clear"></div>
    <div class="ln_solid"></div>
        <div style="text-align:center">
            {% if accion == 'actualizar' %}
            <button type="submit" class="btn btn-success">{% trans "Actualizar"%}</button>
            {% else %}
            <button type="submit" class="btn btn-success">{% trans "Registrar"%}</button>
            {% endif %}
            <a href="/curso/profesor/listado/" class="btn btn-primary">{% trans "Listado"%}</a>
            <a href="/curso/registrar/" class="btn btn-default">{% trans "Limpiar"%}</a>
        <div>
</form>
{% endblock contenido %}

{% block js %}
<script>
    $('#single_cal2').mask('99/99/9999');
	$('#id_telefono, #id_movil, #id_telefono_opcional').mask('999-9999999');
    setTransferFocus($('#form'));
</script>
{% endblock js %}

apps/curso/templates/curso/profesor_eliminar.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "¿Desea Eliminar al Profesor: " %}<strong>{{ object.nombre_profesor }} {{ object.apellido_profesor }}</strong>?<small></small></h2>

</div>
<form method="post" action="" class="form-horizontal form-label-left">
    {% csrf_token%}
    <div class="ln_solid"></div>
    <div style="text-align:center">
        <button type="submit" class="btn btn-danger">{% trans "Sí, Eliminar" %}</button>
        <a href="{% url 'curso:profesor_listado' %}" class="btn btn-primary">{% trans "Cancelar" %}</a>

    </div>
</form>

{% endblock contenido %}