apps/administracion/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from .views import *

urlpatterns = [
    url(r'^conceptos-factura/registrar/$', login_required(Concepto_Factura.as_view()), name='concepto_factura_crear'),
    url(r'^conceptos-factura/listado/$', login_required(Concepto_Factura_Listado.as_view()),
        name='concepto_factura_listado'),
    url(r'^conceptos-factura/editar/(?P<pk>\d+)/$', login_required(Concepto_Factura_Actualizar.as_view()),
        name='concepto_factura_editar'),
    url(r'^conceptos-factura/eliminar/(?P<pk>\d+)/$', login_required(Concepto_Factura_Eliminar.as_view()),
        name='concepto_factura_eliminar'),

    url(r'^costo-curso/$',login_required(Costo_Curso), name='costo_curso'),

    url(r'^cliente/registrar/$',login_required(Cliente_Registro.as_view()), name='cliente_crear'),
    url(r'^cliente/editar/(?P<pk>\d+)/$',login_required(Cliente_Actualizar.as_view()), name='cliente_actualizar'),
    url(r'^cliente/listado/$',login_required(Cliente_Listado.as_view()), name='cliente_listado'),
    
    url(r'^departamento/registrar/$',login_required(Departamento_Crear.as_view()), name='departamento_crear'),
    url(r'^departamento/editar/(?P<pk>\d+)/$', login_required(Departamento_Actualizar.as_view()),
        name='departamento_actualizar'),
    url(r'^departamento/listado', login_required(Departamento_Listado.as_view()), name='departamento_listado'),

    url(r'^configuracion/empresa/subir-logo/$', login_required(Subir_logo), name='logo_empresa'),
    url(r'^configuracion/empresa/$', login_required(configuracion_empresa), name='configurar_empresa'),
]

shool_system/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [

    url(r'^', include('apps.sistema.urls', namespace='sistemas')),
    url(r'^curso/', include('apps.curso.urls', namespace='curso')),
    url(r'^ventas/', include('apps.ventas.urls', namespace='ventas')),
    url(r'^administrativo/', include('apps.administracion.urls', namespace='administracion')),
]

apps/administracion/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


# Create your models here.
class Departamento(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    departamento = models.CharField(max_length=200, verbose_name=_('Departamento'), unique=True)
    estado = models.CharField(max_length=1, default='A',choices=STATUS, verbose_name=_('Estado'))

    def __str__(self):
        return self.departamento

    class Meta:
        db_table = 'tb_adm_departamento'
        verbose_name = 'Departamento'
        verbose_name_plural = 'Departamentos'


class Cliente(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, 'Habilitado'),
        (INACTIVO, 'Inhabilitado'),
    )
    rif_cliente = models.CharField(max_length=14, null=False, blank=False, db_index=True, unique=True,
                                   verbose_name=_('Cédula / Rif'))
    razon_social = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Nombre o Razon Social'))
    direccion_habitacion = models.CharField(max_length=200, null=False, blank=False, verbose_name=_('Dirección'))
    telefono = models.CharField(max_length=12, verbose_name=_('Número de teléfono fijo'))
    telefono_opcional = models.CharField(null=True, blank=True, max_length=12,
                                         verbose_name=_('Número de teléfono opcional'))
    movil = models.CharField(max_length=12, verbose_name=_('Número de teléfono movil'))
    correo = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Correo electrónico'))
    fecha_nacimiento = models.DateField(null=True, blank=True, verbose_name=_('Fecha de nacimiento'))
    empresa_labora = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Empresa donde labora'),
                                      default=_('NO APLICA'))
    cargo = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Cargo que ocupa'),
                             default=_('NO APLICA'))
    antiguedad = models.CharField(max_length=60, null=False, blank=False, verbose_name=_('Antiguedad en la empresa'),
                                  default=_('NO APLICA'))
    estado = models.CharField(max_length=1, choices=STATUS, default='A')

    class Meta:
        db_table = 'tb_adm_cliente'
        verbose_name = 'Cliente'
        verbose_name_plural = 'Clientes'


class ConceptoFactura(models.Model):
    ACTIVO = 'A'
    INACTIVO = 'I'
    STATUS = (
        (ACTIVO, _('Activo')),
        (INACTIVO, _('Inhabilitado')),
    )

    codigo_concepto = models.CharField(max_length=4, db_index=True, blank=False, null=False, unique=True,
                                       verbose_name=_('Código de concepto'))
    descripcion = models.CharField(max_length=30, blank=-False, null=False, verbose_name=_('Descripción del concepto'))
    excento_iva = models.BooleanField(default=False, verbose_name=_('Excento de I.V.A'))
    monto_neto = models.DecimalField(max_digits=10, decimal_places=3, null=False, blank=False,
                                     verbose_name='Monto sin I.V.A')

    estado = models.CharField(max_length=1, default='A', choices=STATUS, verbose_name=_('Estado'))

    def __str__(self):
        return self.codigo_concepto + ' / ' + self.descripcion

    class Meta:
        db_table = 'tb_adm_concepto_factura'
        verbose_name = 'Concepto'
        verbose_name_plural = 'Conceptos'

class Empresa(models.Model):
    codigo_empresa = models.CharField(max_length=20, primary_key=True, verbose_name='Rif')
    logo = models.CharField( blank=True, null=True, max_length=200)
    razon_social = models.CharField(max_length=60, null=False, blank=False, verbose_name='Razon social')
    direccion_fiscal = models.CharField(max_length=200, null=False, blank=False, verbose_name='Dirección fiscal')
    control_factura = models.BigIntegerField(verbose_name='Número de control de facturación')
    correlativo_factura = models.BigIntegerField(verbose_name='Número de factura')
    correlativo_contrato = models.BigIntegerField(verbose_name='Número de control de contratos')
    tasa_iva = models.DecimalField(max_digits=6, decimal_places=2, null=False, blank=False, verbose_name='Tasa de iva')

    class Meta:
        db_table = 'tb_adm_empresa'
        verbose_name = 'Empresa'

apps/administracion/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.http import HttpResponse, HttpResponseRedirect
from django.db import IntegrityError, transaction
from django.core.exceptions import ObjectDoesNotExist
from django.core.urlresolvers import reverse_lazy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.utils.translation import ugettext_lazy as _
from django.views.generic import CreateView, ListView, DeleteView, UpdateView
from apps.curso.models import Curso, Nivel
from .models import Empresa, ConceptoFactura, Cliente, Departamento
from .forms import ConceptoFacturaForm, CostoCursoForm, ClienteForm, EmpresaForm, DepartamentoForm
from apps.sistema.util.File import File
import json

def Subir_logo(request):
    archivo = File(request.FILES['foto'], '', 'logo')
    if not archivo.upload():
        return HttpResponse(json.dumps({'mensaje': str(archivo.mensaje)}), content_type="application/json")


    return HttpResponse(json.dumps({'mensaje': str(archivo.mensaje)}), content_type="application/json")

def configuracion_empresa(request):
    mensaje = ''
    accion = 'grabar'
    if request.method == 'POST':
        if request.POST['accion'] == 'grabar':
            accion = 'grabar'
            form = EmpresaForm(request.POST)
            if form.is_valid():
                file = File(request.FILES['logo_img'], '', 'logo')
                file.upload()

                form_insert = form.save(commit=False)
                form_insert.logo = str(file.getFile())
                form_insert.save()

                HttpResponseRedirect('/administrativo/configuracion/empresa/')
            else:
                messages.add_message(request, messages.WARNING, form.errors)
        else:
            accion = 'update'
            datos = Empresa.objects.all()
            rif = datos[0].codigo_empresa
            form = EmpresaForm(request.POST,instance=Empresa.objects.get(pk=rif))
            if form.is_valid():
                file = File(request.FILES['logo_img'], '', 'logo')
                file.upload()

                form_update = form.save(commit=False)
                form_update.logo = str(file.getFile())
                form_update.save()

                HttpResponseRedirect('/administrativo/configuracion/empresa/')
            else:
                messages.add_message(request, messages.WARNING, form.errors)

    else:
        try:
            datos = Empresa.objects.all()
            rif = datos[0].codigo_empresa
            form = EmpresaForm(instance=Empresa.objects.get(pk=rif))
            accion = 'update'
        except IndexError:
            form = EmpresaForm()


    context = {
        'form': form,
        'titulo': _('Configurar parámetro de la empresa'),
        'accion': accion,
        'mensaje' : _(mensaje)
    }
    return render(request, 'empresa.html', context)

class Departamento_Crear(CreateView):
    model = Departamento
    template_name = 'departamento.html'
    success_url = reverse_lazy('administracion:departamento_listado')
    form_class = DepartamentoForm

    def get_context_data(self, **kwargs):
        context = super(Departamento_Crear, self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = _('Registar departamentos')
        if 'accion' not in context:
            context['accion'] = _('Registrar')

        return context


class Departamento_Actualizar(UpdateView):
    model = Departamento
    template_name = 'departamento.html'
    success_url = reverse_lazy('administracion:departamento_listado')
    form_class = DepartamentoForm

    def get_context_data(self, **kwargs):
        context = super(Departamento_Actualizar,
                        self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = _('Registar departamentos')
        if 'accion' not in context:
            context['accion'] = _('Actualizar')

        return context


class Departamento_Listado(ListView):
    model = Departamento
    template_name = 'departamento_listado.html'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(Departamento_Listado, self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = _('Listado de salones de clases')

        return context
class Concepto_Factura(CreateView):
    model = ConceptoFactura
    form_class = ConceptoFacturaForm
    template_name = 'concepto_factura.html'
    success_url = reverse_lazy('administracion:concepto_factura_listado')

    def get_context_data(self, **kwargs):
        context = super(Concepto_Factura, self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = _('Registar conceptos facturables')


        return context
class Concepto_Factura_Actualizar(UpdateView):
    model = ConceptoFactura
    form_class = ConceptoFacturaForm
    template_name = 'concepto_factura.html'
    success_url = reverse_lazy('administracion:concepto_factura_listado')

    def get_context_data(self, **kwargs):
        context = super(Concepto_Factura_Actualizar, self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = _('Actualizar conceptos facturables')
        if 'accion' not in context:
            context['accion'] = 'actualizar'

        return context

class Concepto_Factura_Listado(ListView):
    model = ConceptoFactura
    paginate_by = 10
    template_name = 'concepto_factura_listado.html'

    def get_context_data(self, **kwargs):
        context = super(Concepto_Factura_Listado, self).get_context_data(**kwargs)
        if 'titulo' not in context:
            context['titulo'] = 'Listado de conceptos facturables'

        return context

class Concepto_Factura_Eliminar(DeleteView):
    model = ConceptoFactura
    success_url = reverse_lazy('administracion:concepto_factura_listado')
    template_name = 'concepto_factura_eliminar.html'

###### asignar costo a cursos ###########

def ajaxCostoCurso(request):
    xHTML = ''
    mensaje = ''
    if request.POST:
        pass
    if request.GET:
        if request.GET['accion'] == 'getCursos':
            try:
                if request.GET['frase'] is not None and len(request.GET['frase']) > 0:                   
                    Cursos = Curso.objects.filter(estado='A', descripcion__contains=request.GET['frase'])                 
                else:
                    Cursos = Curso.objects.filter(estado='A')
                paginator = Paginator(Cursos, 10)   
            except ObjectDoesNotExist:
                return HttpResponse(json.dumps({'mensaje': str(_('No hay cursos creados en el sistema'))}), content_type="application/json")
                
            try:
                page = request.GET['pagina']
                datos = paginator.page(page)                    
            except PageNotAnInteger:
                datos = paginator.page(1)
            except EmptyPage:
                # If page is out of range (e.g. 9999), deliver last page of results.
                datos = paginator.page(paginator.num_pages)
            paginas = datos.previous_page_number
            
            for cursos in datos:
                xHTML += '<tr>'
                xHTML += '<td><a style = "cursor:pointer;" onclick="seleccion_curso(\''+cursos.codigo_curso+'\',\''+cursos.descripcion+'\')">'+cursos.codigo_curso+'<a/></td>'
                xHTML += '<td>'+cursos.descripcion+'</td>'
                xHTML += '</tr>'
            return HttpResponse(json.dumps({'datos': xHTML,'mensaje': '','pagina':str(paginas)}), content_type="application/json")

        if request.GET['accion'] == 'getConceptos':
            ''' catalogo conceptos '''
            datos_conceptos = ConceptoFactura.objects.filter(estado='A')
            for concepto in datos_conceptos:
                xHTML += '<tr>'
                xHTML += '<td><a style = "cursor:pointer" onclick="seleccion_concepto(\''+concepto.codigo_concepto+'\',\''+concepto.descripcion+'\')">'+concepto.codigo_concepto+'</a></td>'
                xHTML += '<td>'+concepto.descripcion+'</td>'
                xHTML += '<td>'+str(concepto.monto_neto)+'</td>'
                xHTML += '</tr>'
            return HttpResponse(json.dumps({'datos': xHTML,'mensaje' : '' }), content_type="application/json")

        if request.GET['accion'] == 'getDatoConcepto':
            try:
                datos_concepto = ConceptoFactura.objects.get(codigo_concepto=request.GET['concepto'])
                return HttpResponse(json.dumps({'descripcion_concepto':datos_concepto.descripcion,'mensaje' : '' }), content_type="application/json")
            except ObjectDoesNotExist:
                mensaje = _('Código de concepto ingresado no existe')
                return HttpResponse(json.dumps({'mensaje': str(mensaje)}), content_type="application/json")

        if request.GET['accion'] == 'getDatosCurso':
            ''' Catalogo de curso '''
            #try:
            datos_curso = Curso.objects.get(codigo_curso=request.GET['curso'])
            datos = Nivel.objects.filter(codigo_curso=request.GET['curso'])

            for niveles in datos:
                xHTML += '<tr>'
                xHTML += '<td><input type = "hidden" name = "codigo_nivel[]" value= "'+niveles.codigo_nivel+'" >'+niveles.codigo_nivel+'</td>'
                xHTML += '<td>'+niveles.descripcion+'</td>'
                xHTML += '<td>'+str(niveles.meses_duracion)+' Meses</td>'
                xHTML += '<td><input type= "number" step="0.001" value = "'+str(niveles.monto_contado)+'" name = "monto_credito[]" id = "monto-contado-'+str(niveles.id)+'" onKeyPress="return soloNumeros(event, this.value)" class="monto_concepto_contado form-control"></td>'

apps/administracion/templates/clientes.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "Clientes" %}<small></small></h2>
    <div class="clearfix"></div>
</div>
<form method="post">
	{% csrf_token %}

    <p class="col-md-3 col-sm-4 col-sx-12">
        <label>{{ form.rif_cliente.label }}</label>
        {{form.rif_cliente}}
    </p>
    <p class="col-md-9 col-sm-8 col-sx-12">
        <label>{{ form.razon_social.label }}</label>
        {{form.razon_social}}
    </p>
    <p class="col-md-4 col-sm-6 col-sx-6">
        <label>{{ form.telefono.label }}</label>
        {{form.telefono}}
    </p>
    <p class="col-md-4 col-sm-6 col-sx-6">
        <label>{{ form.movil.label }}</label>
        {{form.movil}}
    </p>
    <p class="col-md-4 col-sm-6 col-sx-6">
        <label>{{ form.telefono_opcional.label }}</label>
        {{form.telefono_opcional}}
    </p>
    <p class="col-md-4 col-sm-6 col-sx-6">
        <label>{{ form.correo.label }}</label>
        {{form.correo}}
    </p>
    <p class="col-md-3 col-sm-6 col-sx-6">
        <label>{{ form.estado.label }}</label>
        {{form.estado}}
    </p>    
    <div class="clear"></div>
    <p class="col-md-12 col-sm-12 col-sx-12">
        <label>{{ form.direccion_habitacion.label }}</label>
        {{form.direccion_habitacion}}
    </p>  
    <fieldset>
    	<legend>Complete si es persona natural</legend>
    	<p class="col-md-6 col-sm-6 col-sx-12">
	        <label>{{ form.fecha_nacimiento.label }}</label>
	        {{form.fecha_nacimiento}}
	    </p>
    	<p class="col-md-6 col-sm-6 col-sx-12">
	        <label>{{ form.empresa_labora.label }}</label>
	        {{form.empresa_labora}}
	    </p>
	    <p class="col-md-6 col-sm-6 col-sx-12">
	        <label>{{ form.cargo.label }}</label>
	        {{form.cargo}}
	    </p>
	    <p class="col-md-6 col-sm-6 col-sx-12">
	        <label>{{ form.antiguedad.label }}</label>
	        {{form.antiguedad}}
	    </p>

    </fieldset>
    <div class="clear"></div>
    <div class="ln_solid"></div>
    <div style="text-align:center">
    	{% if accion == 'actualizar' %}
        	<button class="btn btn-success">{% trans "Actualizar" %}</button>
        {% else %}
        	<button class="btn btn-success">{% trans "Registrar" %}</button>
        {% endif %}
        <a href="/administrativo/cliente/listado/" class="btn btn-primary">{% trans "Listado" %}</a>
        <a href="/administrativo/cliente/registrar/" class="btn btn-default">{% trans "Limpiar" %}</a>
    </div>
</form>
{% endblock contenido %}


{% block js %}
<script>
    $('#id_rif_cliente').mask('a-999999999');
	$('#single_cal2').datepicker({
      language:'es'

    });
</script>
{% endblock js %}

apps/administracion/templates/concepto_factura.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "Conceptos facturables" %}<small></small></h2>

</div>
<form method="post" id="form" class="form-horizontal form-label-left input_mask">
    {{ form.errors }}
    {% csrf_token %}

    <p class="col-md-3 col-sm-4 col-sx-12">
        <label>{{ form.codigo_concepto.label }}</label>
        {% if accion == 'actualizar' %}
        <input type="text" maxlength="4" name="codigo_concepto" value="{{ form.codigo_concepto.value }}"
               class="form-control" readonly = "readonly" id="id_codigo_concepto">
        {% else %}
        <input type="text" autofocus = "on" maxlength="4" name="codigo_concepto" class="form-control" id="id_codigo_concepto"
               required = "required">
        {% endif %}
    </p>
    <p class="col-md-9 col-sm-8 col-xs-12">
        <label>{{ form.descripcion.label }}</label>
        {{ form.descripcion }}
    </p>
    <p class="col-md-3 col-sm-6 col-xs-12">
        <label>Monto</label>
        {{ form.monto_neto }}
    </p>
    <p class="col-md-2 col-sm-4 col-sx-4">
        <label>{{ form.excento_iva.label }}</label>
        {{ form.excento_iva }}
    </p>
    <div class="clear"></div>
    <p class="col-md-2 col-sm-4 col-xs-6">
        <label>{{ form.estado.label }}</label>
        {{ form.estado }}
    </p>


    <div class="clear"></div>

    <div class="ln_solid"></div>
        <div style="text-align:center">
            {% if accion == 'actualizar' %}
            <button type="submit" class="btn btn-success">{% trans "Actualizar"%}</button>
            {% else %}
            <button type="submit" class="btn btn-success">{% trans "Registrar"%}</button>
            {% endif %}
            <a href="/administrativo/conceptos-factura/listado/" class="btn btn-primary">{% trans "Listado"%}</a>
            <a href="/administrativo/conceptos-factura/registrar/" class="btn btn-default">{% trans "Limpiar"%}</a>
        <div>
</form>
{% endblock contenido %}
{% block js %}

{% endblock js %}

apps/administracion/templates/concepto_factura_eliminar.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "¿Desea Eliminar el concepto: " %}<strong>{{ object.descripcion }}</strong>?<small></small></h2>

</div>
<form method="post" action="" class="form-horizontal form-label-left">
    {% csrf_token%}
    <div class="ln_solid"></div>
    <div style="text-align:center">
        <button type="submit" class="btn btn-danger">{% trans "Sí, Eliminar" %}</button>
        <a href="{% url 'administracion:concepto_factura_listado' %}" class="btn btn-primary">{% trans "Cancelar" %}</a>

    </div>
</form>

{% endblock contenido %}

apps/administracion/templates/departamento.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="box-header">
    <h2 class="box-title">{% trans "Registro de departamentos" %}<small></small></h2>
    <div class="clearfix"></div>
</div>
<form method="post">
    {% csrf_token %}
    <p class="col-md-8 col-sm-8 col-xs-12">
        <label>{{form.departamento.label}}</label>
        {{form.departamento}}
    </p>
    <p class="col-md-4 col-sm-4 col-xs-12">
        <label>{{form.estado.label}}</label>
        {{form.estado}}
    </p>
    <div class="clear"></div>
    <div class="ln_solid"></div>
    <div style="text-align:center">
        <button class="btn btn-success">{{accion}}</button>
        <a href="/administrativo/departamento/listado/" class="btn btn-primary">Listado de departamentos</a>
        <a href="/administrativo/cliente/registrar/" class="btn btn-default">{% trans "Limpiar" %}</a>
    </div>
</form>
{% endblock contenido %}

apps/administracion/templates/empresa.html
{% extends 'base_dashboard.html' %}
{% load i18n %}
{% block contenido %}
<div class="x_panel">
    <div class="x_title">
        <h2>{% trans "Configurar parámetro de la empresa" %}<small></small></h2>    
        <div class="clearfix"></div>
    </div>  
    <form method="post" action="" class="form-horizontal form-label-left input_mask" id="form" enctype="multipart/form-data">
        {% csrf_token %}
        <p class="col-md-2 col-sm-4 col-xs-12">
        	{% if form.logo == 'None'  %}
                <img  src="/static/img/usuario.png" alt="photo profile" id="foto_actual" class="avatar" style="width:100px;" >
            {% else %}
                <img  src="/media/{{form.logo.value}}" alt="photo profile" id="foto_actual" class="avatar" style="width:104px !important;position: relative">
            {% endif %}

        	<input type="file" name="logo_img" id="logo" class="inputfile">
            
            <label for="logo" class = 'seleccionar_foto_perfil'>
                Cargar foto
            </label>
            
        </p>
    	<p class="col-md-4 col-sm-4 col-xs-12">
    		<label>{% trans "Rif" %}</label>
    		{{form.codigo_empresa}}
    	</p>        
    	<p class="col-md-6 col-sm-6 col-xs-12">
    		<label>{% trans "Razon social" %}</label>
    		{{form.razon_social}}
    	</p>
        <div class="clear"></div>
    	
    	<p class="col-md-12 col-sm-12 col-xs-12">
    		<label>{% trans "Dirección fiscal" %}</label>
    		{{form.direccion_fiscal}}
    	</p>
    	<p class="col-md-4 col-sm-4 col-xs-6">
    		<label>{% trans "Correlativo de facturación" %}</label>
    		{{form.correlativo_factura}}
    	</p>
    	<p class="col-md-4 col-sm-4 col-xs-6">
    		<label>{% trans "Correlativo de control" %}</label>
    		{{form.control_factura}}
    	</p>
    	<p class="col-md-4 col-sm-4 col-xs-6">
    		<label>{% trans "Correlativo de contrato" %}</label>
    		{{form.correlativo_contrato}}
    	</p>
    	<p class="col-md-2 col-sm-4 col-xs-6">
    		<label>{% trans "Tasa de Iva" %}</label>
    		{{form.tasa_iva}}
    	</p>
    	<div class="clear"></div>
        <div class="ln_solid"></div>
        
        <button type="submit" class="btn btn-success">{% trans "Registrar" %}</button>
		<input type="hidden" name="accion" value="{{accion}}">
    </form>
</div>
{% endblock contenido %}

{% block js %}
<script>
    $(function(){
        transferFocus( $('#form') );
        $('#id_codigo_empresa').mask('a-999999999');
        $('#logo').change(function(e){
            handleImage(e)
        });
    });
    
    function handleImage(e){
       NProgress.start();
        var reader = new FileReader();
        reader.onload = function(event){
            var image = new Image();
            image.src = e.target.result;
            image.onload = function(){
                if (image.width < 400) {
                    alert("Please choose a larger size");
                    return false;
                } else if (image.height < 300) {
                    alert("Please choose a larger size");
                    return false;
                }
                if(image.height > image.width){
                    alert("Sorry allowed only horizontal images");
                    return false;
                }
                var canvas = document.createElement('canvas');
                var MAX_WIDTH = 200;
                var MAX_HEIGHT = 200;
                var width = image.width;
                var height = image.height;
                if (width > height) {
                    if (width > MAX_WIDTH) {
                        height *= MAX_WIDTH / width;
                        width = MAX_WIDTH;
                    }
                } else {
                    if (height > MAX_HEIGHT) {
                        width *= MAX_HEIGHT / height;
                        height = MAX_HEIGHT;
                    }
                }
                canvas.width = width;
                canvas.height = height;

                var ctx = canvas.getContext('2d');
                ctx.drawImage( image, 0, 0, width, height );

                $('#hidden_image').val(canvas.toDataURL());
                //$('#img_canvas').html(['<img src="', canvas.toDataURL(), '"/>'].join(''));
                $('#foto_actual').attr('src',canvas.toDataURL())

            }
            image.src = event.target.result;

            //subitFotoPerfil();
        }
        reader.readAsDataURL(e.target.files[0]);
        NProgress.done();
    }

</script>
{% endblock js %}